### ISSUE TITLE
Please make the license more clear

### ISSUE THREAD

**Issue by towynlin** [minad/creole#7]
I'm running license auditing tools and am getting warnings about creole having no license, which would technically mean it's copyrighted and no one may use it. Clearly many projects (including sinatra) are using creole, and that's obviously your intent.

- There is no license file.
- The readme says this is "free software" but otherwise just recursively refers to itself.
- The gemspec declares `s.license = 'Ruby'`.
- There is no license named ruby. However, the ruby language is distributed under a [BSD-2-Clause](https://choosealicense.com/licenses/bsd-2-clause/) license.

Please create a LICENSE file with the BSD-2-Clause content linked above, and remove or update the license section of the readme.

**Comment by minad** [comment]
yee, it is bsd-2-clause licensed

**Comment by nathangoulding** [comment]
Can you please add the LICENSE file with the BSD-2 clause content inside? We are running license auditing tools and this is being flagged as well.
